### PR TITLE
add custom headers support for emails

### PR DESCRIPTION
**Pull request by ukby1234**
Looks like the request interceptor doesn't work quite well with dynamic values unless we create a new client for every message. This is to add a custom email headers support with a custom Java annotations.

### CODE REVIEW

**Comment by vitalii-chornobryvyi-swi** [comment]
Also, please add data into:

- CHANGELOG.md above the line 8 and line 70
- README.md above the line 79 and line 88

**Comment by ukby1234** [comment]
@vitalii-chornobryvyi-swi added changelog and readme.

**Comment by vitalii-chornobryvyi-swi** [comment]
> @vitalii-chornobryvyi-swi added changelog and readme.

@ukby1234 nice, please fix also my comment regarding wildcard and we can merge this PR

**Comment by ukby1234** [comment]
@vitalii-chornobryvyi-swi hmm I don’t see your comment about wildcard.

**Comment by vitalii-chornobryvyi-swi** [comment]
@ukby1234 interesting, why the comment is not displayed, anyway it's this one
image

**Comment by ukby1234** [comment]
@vitalii-chornobryvyi-swi fixed imports as well.

**Review by vitalii-chornobryvyi-swi — APPROVED** [review]

**Comment by ukby1234** [comment]
@vitalii-chornobryvyi-swi can you merge this as well? I don't have the permission to merge.

**Pull request merged**
